services:
  mongodb:
    image: mongo:7
    container_name: mongo-db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db
      - ./init-db/init.js:/docker-entrypoint-initdb.d/init.js:ro
    healthcheck:
      test: mongosh -u "admin" -p "secret" --eval "db.adminCommand('ping')" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - shared