services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=sales_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    ports:
      - '6433:5432'
    volumes:
      - ../../mock_data:/mock_data
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d sales_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared