services:
  cassandra:
    image: cassandra:3.11.2
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_AUTHENTICATOR=PasswordAuthenticator"
    restart: always
    volumes:
      - ./out/cassandra_data:/var/lib/cassandra
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh cassandra -u cassandra -p cassandra -e 'SELECT * FROM system.local' 2>/dev/null" ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - shared

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:3.11.2
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./init-db/init.cql:/schema.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -u cassandra -p cassandra -f /schema.cql"
    networks:
      - shared